# Generated by Django 3.2 on 2024-02-06 18:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='gallery_image'),
        ),
    ]
